# -*- coding: utf-8 -*-
"""Dynamic_array.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RlggBnj3JOxLbdvJeahlRIDHh_c7dRcA
"""

import ctypes

class Mylist():
  def __init__(self, size):
    self.size=size
    self.n=0
    self.A=self.__make_array(self.size)


  def __make_array(self,capacity):
    return(capacity*ctypes.py_object)()

l=Mylist(4)
print(l.size)
print(type(l))

